### Weekly Report Python Notebook

#### Run all cells by pressing "Run All"

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Input file name:

```python
WR_KT_df = pd.read_csv("<file_name>", thousands=',')  
```
#### Replace <file_name> with the name of the csv file that is going to be analyzed

#### Keep the file in the same directory as the WeeklyReport.ipynb file

In [8]:
WR_KT_df = pd.read_csv(r"C:\Users\Daraz\Documents\ddda\DiagnosticAnalysisDataset\2022_08010823_DA.csv", thousands=',')
# WR_KT_overview = pd.read_csv('WeeklyReport19.csv')

In [9]:
# WR_KT_overview.head()
# WR_KT_overview = WR_KT_overview.iloc[[0]]
# WR_KT_overview = WR_KT_overview.rename(columns={'Chats': 'Total chat sessions:', 'Session Resolved Rate': 'Resolution Rate, RR:', 'Session No Answer Rate': 'No Answer Rate:'})
# WR_KT_overview = WR_KT_overview[['Total chat sessions:', 'Resolution Rate, RR:','Switch to Live Agent Rate', 'No Answer Rate:']]
# WR_KT_overview_report = WR_KT_overview.T
# WR_KT_overview_report
# WR_KT_overview_report = WR_KT_overview.T

In [10]:
WR_KT_df.columns

Index(['date_id', 'tenant_name', 'robot_code_name', 'from_name',
       'Knowledge Type', 'Knowledge Id', 'Knowledge Name', 'Solution Id',
       'Solution Name', 'Chats', 'sid_cnt', 'Session_Resolved_Rate',
       'Switch_to_Live_Agent_Rate', 'Survey_Response_Rate',
       'Chat_Unsatisfied_Rate'],
      dtype='object')

### Testing

In [11]:
WR_KT_df[WR_KT_df['robot_code_name'] == 'BD-Daz-EN'].head(10)

,date_id,tenant_name,robot_code_name,from_name,Knowledge Type,Knowledge Id,Knowledge Name,Solution Id,Solution Name,Chats,sid_cnt,Session_Resolved_Rate,Switch_to_Live_Agent_Rate,Survey_Response_Rate,Chat_Unsatisfied_Rate
0,2022-08-16 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1859,918,0.574700,0.359869,0.0,NaN
1,2022-08-15 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1386,669,0.898356,0.000000,0.0,NaN
2,2022-08-07 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1302,818,0.506112,0.460880,0.0,NaN
3,2022-08-03 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1173,493,0.554878,0.402439,0.0,NaN
4,2022-08-14 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1161,601,0.538333,0.428333,0.0,NaN
5,2022-08-08 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1154,700,0.610873,0.317597,0.0,NaN
6,2022-08-16 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,小招,1000055995,Greeting,NaN,NaN,1128,498,0.782696,0.175050,0.0,NaN
7,2022-08-17 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1111,613,0.570962,0.391517,0.0,NaN
8,2022-08-04 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1086,587,0.631399,0.295222,0.0,NaN
9,2022-08-13 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1032,614,0.516287,0.436482,0.0,NaN

In [12]:
WR_KT_df.describe()

,Knowledge Id,Solution Id,Chats,sid_cnt,Session_Resolved_Rate,Switch_to_Live_Agent_Rate,Survey_Response_Rate,Chat_Unsatisfied_Rate
count,2.622300e+04,3089.000000,26223.000000,26223.000000,26195.000000,26195.000000,26223.000000,4459.000000
mean,1.000041e+09,176127.285206,21.296343,17.305838,0.784565,0.159205,0.044310,0.598159
std,2.501215e+04,15419.665424,71.629329,53.101306,0.299520,0.264778,0.157585,0.436753
min,1.000015e+09,150113.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000017e+09,175762.000000,1.000000,1.000000,0.666667,0.000000,0.000000,0.000000
50%,1.000028e+09,181555.000000,3.000000,2.000000,0.940217,0.000000,0.000000,0.800000
75%,1.000070e+09,183519.000000,9.000000,8.000000,1.000000,0.240000,0.000000,1.000000
max,1.000079e+09,195101.000000,1859.000000,918.000000,1.000000,1.000000,1.000000,1.000000

In [13]:
WR_KT_df[WR_KT_df['robot_code_name'] == 'BD-Daz-EN'].head(2)

,date_id,tenant_name,robot_code_name,from_name,Knowledge Type,Knowledge Id,Knowledge Name,Solution Id,Solution Name,Chats,sid_cnt,Session_Resolved_Rate,Switch_to_Live_Agent_Rate,Survey_Response_Rate,Chat_Unsatisfied_Rate
0,2022-08-16 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1859,918,0.574700,0.359869,0.0,NaN
1,2022-08-15 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1386,669,0.898356,0.000000,0.0,NaN

In [14]:
WR_KT_df['Chat_Unsatisfied_Rate'].count()

4459

In [15]:
WR_KT_df.shape

(26223, 15)

In [16]:
WR_KT_df_LC = WR_KT_df[WR_KT_df['robot_code_name'] == 'BD-Daz-LC']
WR_KT_df_EN = WR_KT_df[WR_KT_df['robot_code_name'] == 'BD-Daz-EN']

# WR_KT_df_LC = WR_KT_df
# WR_KT_df_EN = WR_KT_df

In [17]:
WR_KT_df_LC.head()

,date_id,tenant_name,robot_code_name,from_name,Knowledge Type,Knowledge Id,Knowledge Name,Solution Id,Solution Name,Chats,sid_cnt,Session_Resolved_Rate,Switch_to_Live_Agent_Rate,Survey_Response_Rate,Chat_Unsatisfied_Rate
12,2022-08-18 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),969,702,0.867521,0.064103,0.148607,0.243056
15,2022-08-15 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),939,662,0.939577,0.000000,0.122471,0.173913
31,2022-08-20 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),790,606,0.902640,0.049505,0.139241,0.136364
33,2022-08-14 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),786,555,0.882883,0.061261,0.136132,0.168224
35,2022-08-16 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),771,565,0.904425,0.038938,0.111543,0.186047

In [18]:
WR_KT_df_LC = WR_KT_df_LC.reset_index()
WR_KT_df_EN = WR_KT_df_EN.reset_index()

### Total session Resolved

#### For EN

In [19]:
WR_KT_df_EN['total_session_resolved'] = 0
for i in range(len(WR_KT_df_EN)):
    WR_KT_df_EN['total_session_resolved'][i] = WR_KT_df_EN['sid_cnt'][i] * WR_KT_df_EN['Session_Resolved_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/3405667219.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_EN['total_session_resolved'][i] = WR_KT_df_EN['sid_cnt'][i] * WR_KT_df_EN['Session_Resolved_Rate'][i]

#### For LC

In [20]:
WR_KT_df_LC['total_session_resolved'] = 0
for i in range(len(WR_KT_df_LC)):
    WR_KT_df_LC['total_session_resolved'][i] = WR_KT_df_LC['sid_cnt'][i] * WR_KT_df_LC['Session_Resolved_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/2991021005.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_LC['total_session_resolved'][i] = WR_KT_df_LC['sid_cnt'][i] * WR_KT_df_LC['Session_Resolved_Rate'][i]

### Total count for switch to live agent

#### For EN

In [21]:
WR_KT_df_EN['total_switch_agent'] = 0
for i in range(len(WR_KT_df_LC)):
    WR_KT_df_EN['total_switch_agent'][i] = WR_KT_df_EN['sid_cnt'][i] * WR_KT_df_EN['Switch_to_Live_Agent_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/2183224985.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_EN['total_switch_agent'][i] = WR_KT_df_EN['sid_cnt'][i] * WR_KT_df_EN['Switch_to_Live_Agent_Rate'][i]

#### For LC

In [22]:
WR_KT_df_LC['total_switch_agent'] = 0
for i in range(len(WR_KT_df_LC)):
    WR_KT_df_LC['total_switch_agent'][i] = WR_KT_df_LC['sid_cnt'][i] * WR_KT_df_LC['Switch_to_Live_Agent_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/445463113.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_LC['total_switch_agent'][i] = WR_KT_df_LC['sid_cnt'][i] * WR_KT_df_LC['Switch_to_Live_Agent_Rate'][i]

### Response Count (Chat)

#### For EN

In [23]:
WR_KT_df_EN['response_count'] = 0
for i in range(len(WR_KT_df_EN)):
    WR_KT_df_EN['response_count'][i] = WR_KT_df_EN['Chats'][i] * WR_KT_df_EN['Survey_Response_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/1695637170.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_EN['response_count'][i] = WR_KT_df_EN['Chats'][i] * WR_KT_df_EN['Survey_Response_Rate'][i]

#### For LC

In [24]:
WR_KT_df_LC['response_count'] = 0
for i in range(len(WR_KT_df_LC)):
    WR_KT_df_LC['response_count'][i] = WR_KT_df_LC['Chats'][i] * WR_KT_df_LC['Survey_Response_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/1577773350.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_LC['response_count'][i] = WR_KT_df_LC['Chats'][i] * WR_KT_df_LC['Survey_Response_Rate'][i]

### Unsatisfied Count

#### For EN

In [25]:
WR_KT_df_EN['unsatisfied_count'] = 0
for i in range(len(WR_KT_df_EN)):
    WR_KT_df_EN['unsatisfied_count'][i] = WR_KT_df_EN['response_count'][i] * WR_KT_df_EN['Chat_Unsatisfied_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/1058022223.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_EN['unsatisfied_count'][i] = WR_KT_df_EN['response_count'][i] * WR_KT_df_EN['Chat_Unsatisfied_Rate'][i]

#### For LC

In [26]:
WR_KT_df_LC['unsatisfied_count'] = 0
for i in range(len(WR_KT_df_LC)):
    WR_KT_df_LC['unsatisfied_count'][i] = WR_KT_df_LC['response_count'][i] * WR_KT_df_LC['Chat_Unsatisfied_Rate'][i]

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/1040255940.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_LC['unsatisfied_count'][i] = WR_KT_df_LC['response_count'][i] * WR_KT_df_LC['Chat_Unsatisfied_Rate'][i]

In [27]:
WR_KT_df_EN.head(4)

,index,date_id,tenant_name,robot_code_name,from_name,Knowledge Type,Knowledge Id,Knowledge Name,Solution Id,Solution Name,Chats,sid_cnt,Session_Resolved_Rate,Switch_to_Live_Agent_Rate,Survey_Response_Rate,Chat_Unsatisfied_Rate,total_session_resolved,total_switch_agent,response_count,unsatisfied_count
0,0,2022-08-16 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1859,918,0.574700,0.359869,0.0,NaN,527.574700,330.359869,0.0,NaN
1,1,2022-08-15 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1386,669,0.898356,0.000000,0.0,NaN,601.000000,0.000000,0.0,NaN
2,2,2022-08-07 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1302,818,0.506112,0.460880,0.0,NaN,414.000000,377.000000,0.0,NaN
3,3,2022-08-03 00:00:00,Alime-DRZ-CC-BD,BD-Daz-EN,BD-Daz-EN-HC-App,大招,1000068200,Need help,NaN,NaN,1173,493,0.554878,0.402439,0.0,NaN,273.554878,198.402439,0.0,NaN

In [28]:
WR_KT_df_LC.head(4)

,index,date_id,tenant_name,robot_code_name,from_name,Knowledge Type,Knowledge Id,Knowledge Name,Solution Id,Solution Name,Chats,sid_cnt,Session_Resolved_Rate,Switch_to_Live_Agent_Rate,Survey_Response_Rate,Chat_Unsatisfied_Rate,total_session_resolved,total_switch_agent,response_count,unsatisfied_count
0,12,2022-08-18 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),969,702,0.867521,0.064103,0.148607,0.243056,609.0,45.0,144.0,35.0
1,15,2022-08-15 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),939,662,0.939577,0.000000,0.122471,0.173913,622.0,0.0,115.0,20.0
2,31,2022-08-20 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),790,606,0.902640,0.049505,0.139241,0.136364,547.0,30.0,110.0,15.0
3,33,2022-08-14 00:00:00,Alime-DRZ-CC-BD,BD-Daz-LC,BD-Daz-LC-DD-App,FAQ,1000069823,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,193869.0,Item don't delivered(with estimated date) (Local),786,555,0.882883,0.061261,0.136132,0.168224,490.0,34.0,107.0,18.0

In [29]:
WR_KT_df_EN = WR_KT_df_EN.fillna(0)
WR_KT_df_LC = WR_KT_df_LC.fillna(0)

In [30]:
WR_KT_df_EN[['total_session_resolved','total_switch_agent','response_count','unsatisfied_count']]

,total_session_resolved,total_switch_agent,response_count,unsatisfied_count
0,527.574700,330.359869,0.0,0.0
1,601.000000,0.000000,0.0,0.0
2,414.000000,377.000000,0.0,0.0
3,273.554878,198.402439,0.0,0.0
4,323.538333,257.428333,0.0,0.0
...,...,...,...,...
18744,0.000000,0.000000,0.0,0.0
18745,1.000000,0.000000,0.0,0.0
18746,1.000000,0.000000,0.0,0.0
18747,1.000000,0.000000,0.0,0.0
18748,1.000000,0.000000,0.0,0.0

In [31]:
WR_KT_df_LC[['total_session_resolved','total_switch_agent','response_count','unsatisfied_count']]

,total_session_resolved,total_switch_agent,response_count,unsatisfied_count
0,609.0,45.0,144.0,35.0
1,622.0,0.0,115.0,20.0
2,547.0,30.0,110.0,15.0
3,490.0,34.0,107.0,18.0
4,511.0,22.0,86.0,16.0
...,...,...,...,...
7450,1.0,0.0,0.0,0.0
7451,1.0,0.0,0.0,0.0
7452,1.0,0.0,0.0,0.0
7453,1.0,0.0,0.0,0.0
7454,1.0,0.0,1.0,0.0

### Pivot Table for

In [32]:
WR_KT_df_EN_pivot =  pd.pivot_table(WR_KT_df_EN, values=['Chats','sid_cnt','total_session_resolved','total_switch_agent','unsatisfied_count'], index= ['Knowledge Name'], aggfunc = np.sum)
WR_KT_df_LC_pivot = pd.pivot_table(WR_KT_df_LC, values=['Chats','sid_cnt','total_session_resolved','total_switch_agent','unsatisfied_count'], index= ['Knowledge Name'], aggfunc = np.sum)

In [33]:
WR_KT_df_LC_pivot.head(20)

,Chats,sid_cnt,total_session_resolved,total_switch_agent,unsatisfied_count
Knowledge Name,,,,,
Ata refund pete koto din lagbe,2,2,1.000000,0.000000,0.0
Cancellation_GuidedFlow_LC,686,669,583.000000,59.000000,0.0
Garbage Collector LC,116,97,87.000000,7.000000,0.0
Live Chat: Agent Specialization - Eng,16,16,8.000000,3.000000,0.0
Live Chat: Agent Specialization - Local,35,32,18.500000,8.500000,0.0
Payment_GuidedFlow_LC,944,932,748.662602,142.171635,0.0
Refund_GuidedFlow_LC,694,682,570.000000,89.000000,0.0
Return_GuidedFlow_LC,1031,1005,861.000000,107.000000,0.0
WIMO_GuidedFlow_LC,3118,3044,2473.000000,424.000000,0.0
account_deletion_form,1,1,1.000000,0.000000,0.0
অনলাইন রিটার্ন ফর্ম কিভাবে পূরণ করবো ?,2,2,1.000000,1.000000,0.0
অন্যান্য বিষয় প্রশ্ন,4555,4314,2184.481074,1940.329060,1.0
অর্ডার কনফার্মড হওয়ার পর কি নোটিফাই করবেন?,157,153,110.000000,31.000000,6.0
অর্ডার করার পর কতক্ষন পর্যন্ত পেমেন্ট করা যাবে?,2,2,1.000000,0.000000,0.0
অর্ডার করেছি কিন্তু এখনো পেমেন্ট করিনি,12,12,12.000000,0.000000,0.0
অর্ডার কিভাবে বাতিল করব?,7665,6232,5443.840909,426.159091,144.0
অর্ডার প্লেস করতে পারছি না কেন?,6544,6201,5408.000000,508.000000,96.0
অর্ডার প্লেস করার পর কি পেমেন্ট মেথড চেঞ্জ করতে পারবো?,46,44,33.000000,7.000000,1.0
অর্ডার বাতিল হলে রিফান্ড কিভাবে করা হয় ?,245,225,183.000000,28.000000,8.0
অর্ডার সক্রান্ত প্রশ্ন,4091,3802,2461.617021,1121.319149,0.0

In [34]:
WR_KT_df_LC_pivot.head(20)

,Chats,sid_cnt,total_session_resolved,total_switch_agent,unsatisfied_count
Knowledge Name,,,,,
Ata refund pete koto din lagbe,2,2,1.000000,0.000000,0.0
Cancellation_GuidedFlow_LC,686,669,583.000000,59.000000,0.0
Garbage Collector LC,116,97,87.000000,7.000000,0.0
Live Chat: Agent Specialization - Eng,16,16,8.000000,3.000000,0.0
Live Chat: Agent Specialization - Local,35,32,18.500000,8.500000,0.0
Payment_GuidedFlow_LC,944,932,748.662602,142.171635,0.0
Refund_GuidedFlow_LC,694,682,570.000000,89.000000,0.0
Return_GuidedFlow_LC,1031,1005,861.000000,107.000000,0.0
WIMO_GuidedFlow_LC,3118,3044,2473.000000,424.000000,0.0
account_deletion_form,1,1,1.000000,0.000000,0.0
অনলাইন রিটার্ন ফর্ম কিভাবে পূরণ করবো ?,2,2,1.000000,1.000000,0.0
অন্যান্য বিষয় প্রশ্ন,4555,4314,2184.481074,1940.329060,1.0
অর্ডার কনফার্মড হওয়ার পর কি নোটিফাই করবেন?,157,153,110.000000,31.000000,6.0
অর্ডার করার পর কতক্ষন পর্যন্ত পেমেন্ট করা যাবে?,2,2,1.000000,0.000000,0.0
অর্ডার করেছি কিন্তু এখনো পেমেন্ট করিনি,12,12,12.000000,0.000000,0.0
অর্ডার কিভাবে বাতিল করব?,7665,6232,5443.840909,426.159091,144.0
অর্ডার প্লেস করতে পারছি না কেন?,6544,6201,5408.000000,508.000000,96.0
অর্ডার প্লেস করার পর কি পেমেন্ট মেথড চেঞ্জ করতে পারবো?,46,44,33.000000,7.000000,1.0
অর্ডার বাতিল হলে রিফান্ড কিভাবে করা হয় ?,245,225,183.000000,28.000000,8.0
অর্ডার সক্রান্ত প্রশ্ন,4091,3802,2461.617021,1121.319149,0.0

In [35]:
WR_KT_df_LC_pivot['sid_cnt']

Knowledge Name
Ata refund pete koto din lagbe               2
Cancellation_GuidedFlow_LC                 669
Garbage Collector LC                        97
Live Chat: Agent Specialization - Eng       16
Live Chat: Agent Specialization - Local     32
                                          ...
সেলারের নামে কমপ্লেইন করবো কিভাবে ?         29
স্টিকার প্রাইস কিভাবে সংগ্রহ করবো?          38
হট ডিলস অফার কি ?                            5
১ টাকার গেম কিভাবে খেলবো ?                   6
১১ ও ক্লক ডিলস কী?                          35
Name: sid_cnt, Length: 348, dtype: int64

In [36]:
WR_KT_df_EN_pivot = WR_KT_df_EN_pivot.sort_values('sid_cnt', ascending=0)
WR_KT_df_LC_pivot = WR_KT_df_LC_pivot.sort_values('sid_cnt', ascending=0)

### RR Calculation

In [37]:
WR_KT_df_EN_pivot = WR_KT_df_EN_pivot.reset_index()
WR_KT_df_LC_pivot = WR_KT_df_LC_pivot.reset_index()

In [38]:
WR_KT_df_LC_pivot

,Knowledge Name,Chats,sid_cnt,total_session_resolved,total_switch_agent,unsatisfied_count
0,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,40231,29005,24530.342753,2661.442742,1295.0
1,আমার সাহায্য লাগবে,21687,17246,10736.183997,5710.407077,6.0
2,কালেকশন পয়েন্ট কোন সময়ে খোলা থাকবে?,11130,8610,7500.333436,773.478239,144.0
3,অর্ডার কিভাবে বাতিল করব?,7665,6232,5443.840909,426.159091,144.0
4,অর্ডার প্লেস করতে পারছি না কেন?,6544,6201,5408.000000,508.000000,96.0
...,...,...,...,...,...,...
343,দারাজ টপ আপ কী?,1,1,0.000000,1.000000,0.0
344,দারাজ গিফট কার্ড কেনার পেমেন্ট মেথড কি?,1,1,0.000000,1.000000,0.0
345,মেগা ডিলস অফার কি ?,1,1,1.000000,0.000000,0.0
346,আমি কবে রিফান্ড পাবো,1,1,0.000000,1.000000,0.0
347,ডেলিভারি দেরী হওয়ার কারণ গুলো কি কি ?,1,1,1.000000,0.000000,0.0

In [39]:
WR_KT_df_EN_pivot.head(2)

,Knowledge Name,Chats,sid_cnt,total_session_resolved,total_switch_agent,unsatisfied_count
0,How can I track my order,43870,34444,28579.250365,4355.969003,456.0
1,Need help,41543,27429,17370.019353,8803.377798,0.0

In [40]:
WR_KT_df_LC_pivot.head(2)

,Knowledge Name,Chats,sid_cnt,total_session_resolved,total_switch_agent,unsatisfied_count
0,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,40231,29005,24530.342753,2661.442742,1295.0
1,আমার সাহায্য লাগবে,21687,17246,10736.183997,5710.407077,6.0

#### For EN

In [41]:
WR_KT_df_EN_pivot['RR'] = 0
for i in range(len(WR_KT_df_EN_pivot)):
    WR_KT_df_EN_pivot['RR'][i] = (WR_KT_df_EN_pivot['total_session_resolved'][i] / WR_KT_df_EN_pivot['sid_cnt'][i]) * 100

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/341082290.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_EN_pivot['RR'][i] = (WR_KT_df_EN_pivot['total_session_resolved'][i] / WR_KT_df_EN_pivot['sid_cnt'][i]) * 100

#### For LC

In [42]:
WR_KT_df_LC_pivot['RR'] = 0
for i in range(len(WR_KT_df_LC_pivot)):
    WR_KT_df_LC_pivot['RR'][i] = (WR_KT_df_LC_pivot['total_session_resolved'][i] / WR_KT_df_LC_pivot['sid_cnt'][i]) * 100

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/3149250145.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_LC_pivot['RR'][i] = (WR_KT_df_LC_pivot['total_session_resolved'][i] / WR_KT_df_LC_pivot['sid_cnt'][i]) * 100

### STA Calculation

#### EN

In [43]:
WR_KT_df_EN_pivot['STA'] = 0
for i in range(len(WR_KT_df_EN_pivot)):
    WR_KT_df_EN_pivot['STA'][i] = (WR_KT_df_EN_pivot['total_switch_agent'][i] / WR_KT_df_EN_pivot['sid_cnt'][i])*100

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/2769942859.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_EN_pivot['STA'][i] = (WR_KT_df_EN_pivot['total_switch_agent'][i] / WR_KT_df_EN_pivot['sid_cnt'][i])*100

#### LC

In [44]:
WR_KT_df_LC_pivot['STA'] = 0
for i in range(len(WR_KT_df_LC_pivot)):
    WR_KT_df_LC_pivot['STA'][i] = (WR_KT_df_LC_pivot['total_switch_agent'][i] / WR_KT_df_LC_pivot['sid_cnt'][i])*100

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/130131208.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_LC_pivot['STA'][i] = (WR_KT_df_LC_pivot['total_switch_agent'][i] / WR_KT_df_LC_pivot['sid_cnt'][i])*100

### UR Calculation

#### EN

In [45]:
WR_KT_df_EN_pivot['UR'] = 0
for i in range(len(WR_KT_df_EN_pivot)):
    WR_KT_df_EN_pivot['UR'][i] = (WR_KT_df_EN_pivot['unsatisfied_count'][i] / WR_KT_df_EN_pivot['Chats'][i])*100

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/3326779036.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_EN_pivot['UR'][i] = (WR_KT_df_EN_pivot['unsatisfied_count'][i] / WR_KT_df_EN_pivot['Chats'][i])*100

#### LC

In [46]:
WR_KT_df_LC_pivot['UR'] = 0
for i in range(len(WR_KT_df_LC_pivot)):
    WR_KT_df_LC_pivot['UR'][i] = (WR_KT_df_LC_pivot['unsatisfied_count'][i] / WR_KT_df_LC_pivot['Chats'][i])*100

C:\Users\Daraz\AppData\Local\Temp/ipykernel_10900/620173858.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  WR_KT_df_LC_pivot['UR'][i] = (WR_KT_df_LC_pivot['unsatisfied_count'][i] / WR_KT_df_LC_pivot['Chats'][i])*100

### Top KTs for LC Chatbot

In [47]:
WR_KT_df_LC_pivot

,Knowledge Name,Chats,sid_cnt,total_session_resolved,total_switch_agent,unsatisfied_count,RR,STA,UR
0,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,40231,29005,24530.342753,2661.442742,1295.0,84.572807,9.175807,3.218911
1,আমার সাহায্য লাগবে,21687,17246,10736.183997,5710.407077,6.0,62.253183,33.111487,0.027666
2,কালেকশন পয়েন্ট কোন সময়ে খোলা থাকবে?,11130,8610,7500.333436,773.478239,144.0,87.111887,8.983487,1.293801
3,অর্ডার কিভাবে বাতিল করব?,7665,6232,5443.840909,426.159091,144.0,87.353031,6.838240,1.878669
4,অর্ডার প্লেস করতে পারছি না কেন?,6544,6201,5408.000000,508.000000,96.0,87.211740,8.192227,1.466993
...,...,...,...,...,...,...,...,...,...
343,দারাজ টপ আপ কী?,1,1,0.000000,1.000000,0.0,0.000000,100.000000,0.000000
344,দারাজ গিফট কার্ড কেনার পেমেন্ট মেথড কি?,1,1,0.000000,1.000000,0.0,0.000000,100.000000,0.000000
345,মেগা ডিলস অফার কি ?,1,1,1.000000,0.000000,0.0,100.000000,0.000000,0.000000
346,আমি কবে রিফান্ড পাবো,1,1,0.000000,1.000000,0.0,0.000000,100.000000,0.000000
347,ডেলিভারি দেরী হওয়ার কারণ গুলো কি কি ?,1,1,1.000000,0.000000,0.0,100.000000,0.000000,0.000000

In [48]:
WR_KT_df_LC_pivot_ = WR_KT_df_LC_pivot[['Knowledge Name', 'sid_cnt', 'RR', 'STA', 'UR']].head(15)

In [49]:
WR_KT_df_LC_pivot_

,Knowledge Name,sid_cnt,RR,STA,UR
0,আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?,29005,84.572807,9.175807,3.218911
1,আমার সাহায্য লাগবে,17246,62.253183,33.111487,0.027666
2,কালেকশন পয়েন্ট কোন সময়ে খোলা থাকবে?,8610,87.111887,8.983487,1.293801
3,অর্ডার কিভাবে বাতিল করব?,6232,87.353031,6.838240,1.878669
4,অর্ডার প্লেস করতে পারছি না কেন?,6201,87.211740,8.192227,1.466993
5,আরো সাহায্য প্রয়োজন (Need more help),5952,49.857094,45.687385,0.000000
6,কার্ট থেকে অর্ডার করবো কিভাবে?,5037,91.721263,4.546357,1.843241
7,কত দ্রুত আমি আমার অর্ডার পেতে পারি?,4684,87.937660,7.728437,1.330008
8,আমার অর্ডার আসতে দেরি হচ্ছে কেন ?,4398,76.443838,17.212369,2.665827
9,অন্যান্য বিষয় প্রশ্ন,4314,50.637021,44.977493,0.021954
10,অর্ডার সক্রান্ত প্রশ্ন,3802,64.745319,29.492876,0.000000
11,WIMO_GuidedFlow_LC,3044,81.241787,13.929041,0.000000
12,শিপিং এবং ডেলিভেরি সক্রান্ত প্রশ্ন,2890,62.614907,32.710799,0.033003
13,রিফান্ড প্রসেস শেষ হতে কতদিন লাগবে?,2601,81.770633,11.845604,1.262799
14,গ্রিটিং পোষ্ট-ম্যাচ,2366,74.500687,16.985547,0.000000

In [50]:
WR_KT_df_LC_pivot_.round({"RR" : 2, 'STA': 2, 'UR' : 2})

                            Knowledge Name  sid_cnt     RR    STA    UR
0   আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?    29005  84.57   9.18  3.22
1                       আমার সাহায্য লাগবে    17246  62.25  33.11  0.03
2      কালেকশন পয়েন্ট কোন সময়ে খোলা থাকবে?     8610  87.11   8.98  1.29
3                 অর্ডার কিভাবে বাতিল করব?     6232  87.35   6.84  1.88
4          অর্ডার প্লেস করতে পারছি না কেন?     6201  87.21   8.19  1.47
5    আরো সাহায্য প্রয়োজন (Need more help)     5952  49.86  45.69  0.00
6           কার্ট থেকে অর্ডার করবো কিভাবে?     5037  91.72   4.55  1.84
7      কত দ্রুত আমি আমার অর্ডার পেতে পারি?     4684  87.94   7.73  1.33
8        আমার অর্ডার আসতে দেরি হচ্ছে কেন ?     4398  76.44  17.21  2.67
9                     অন্যান্য বিষয় প্রশ্ন     4314  50.64  44.98  0.02
10                  অর্ডার সক্রান্ত প্রশ্ন     3802  64.75  29.49  0.00
11                      WIMO_GuidedFlow_LC     3044  81.24  13.93  0.00
12      শিপিং এবং ডেলিভেরি সক্রান্ত প্রশ্ন     2890  62.61  32.71  0.03
13     রিফান্ড প্রসেস শেষ হতে কতদিন লাগবে?     2601  81.77  11.85  1.26
14                     গ্রিটিং পোষ্ট-ম্যাচ     2366  74.50  16.99  0.00

In [51]:
WR_KT_df_LC_pivot[['Knowledge Name', 'sid_cnt']].head(10)

                           Knowledge Name  sid_cnt
0  আমার অর্ডার কিভাবে ট্র্যাক করতে পারবো?    29005
1                      আমার সাহায্য লাগবে    17246
2     কালেকশন পয়েন্ট কোন সময়ে খোলা থাকবে?     8610
3                অর্ডার কিভাবে বাতিল করব?     6232
4         অর্ডার প্লেস করতে পারছি না কেন?     6201
5   আরো সাহায্য প্রয়োজন (Need more help)     5952
6          কার্ট থেকে অর্ডার করবো কিভাবে?     5037
7     কত দ্রুত আমি আমার অর্ডার পেতে পারি?     4684
8       আমার অর্ডার আসতে দেরি হচ্ছে কেন ?     4398
9                    অন্যান্য বিষয় প্রশ্ন     4314

In [52]:
WR_KT_df_LC_pivot[['Knowledge Name', 'sid_cnt']].head(5).to_clipboard()

### Top KTs for EN Chatbot

In [ ]:
# WIMO_GuidedFlow_EN
# Cancellation_GuidedFlow_EN
# Payment_GuidedFlow_EN
# Refund_GuidedFlow_EN
# Return_GuidedFlow_EN

In [62]:
kt_list = ['WIMO_GuidedFlow_EN', 'Cancellation_GuidedFlow_EN', 'Payment_GuidedFlow_EN', 'Refund_GuidedFlow_EN', 'Return_GuidedFlow_EN']

In [67]:
WR_KT_df_EN_pivot[WR_KT_df_EN_pivot['Knowledge Name'].isin(kt_list)][['Knowledge Name', 'sid_cnt', 'RR']]

                Knowledge Name  sid_cnt         RR
9           WIMO_GuidedFlow_EN     8377  72.791607
19       Payment_GuidedFlow_EN     2937  77.868573
27        Return_GuidedFlow_EN     2114  80.368969
28  Cancellation_GuidedFlow_EN     2104  83.079848
31        Refund_GuidedFlow_EN     1919  76.915060

In [64]:
WR_KT_df_EN_pivot[['Knowledge Name', 'sid_cnt']].head(10)

                                Knowledge Name  sid_cnt
0                     How can I track my order    34444
1                                    Need help    27429
2                                     Greeting    23491
3                       How to cancel my order    15736
4  How long does it take to receive my product    13849
5                         Can I return an Item    12263
6        My order is delayed. What should I do     8704
7                                Talk to Agent     8483
8                               Need more help     8457
9                           WIMO_GuidedFlow_EN     8377

In [55]:
WR_KT_df_EN_pivot[['Knowledge Name', 'sid_cnt']].head(5).to_clipboard()

In [56]:
W_KT_DF = pd.concat([WR_KT_df_EN_pivot, WR_KT_df_LC_pivot])

### Redundant Cell

In [57]:
# pandas.DataFrame.to_clipboard
# total_sessions = WR_KT_overview['Sessions'].sum()
# RR = WR_KT_overview['Session Resolved Rate']

# WR_KT_overview['Session Resolved Rate'] = WR_KT_overview['Session Resolved Rate'].str.rstrip(
#     "%").astype(float)/100

# WR_KT_overview['Session Resolved Rate'].sum(
# ) / WR_KT_overview['Session Resolved Rate'].count()

# WR_KT_overview['Session Resolved Rate'].count()

# df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=['A', 'B', 'C'])
# df.to_clipboard()

#20220606
# 20220612
#